# Generated by Django 4.1.1 on 2022-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_desc', models.TextField()),
                ('hotel_image', models.ImageField(upload_to='hotel_pics/')),
                ('price', models.FloatField()),
                ('amenities', models.ManyToManyField(to='Hotel.amenities')),
            ],
        ),
    ]
